services:
  auth:
    image: rmedicharla/auth
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./private_key.pem:/etc/ssl/private/private_key.pem
      - store:/app/store

volumes:
  store:
    driver: local