# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefs < Formula
  desc "a cli tool to simplify the process of creating, testing, and deploying full stack applications onto kubernetes clusters."
  homepage "https://github.com/rahulmedicharla/kubefs"
  version "1.2.0"
  license "MIT"

  depends_on "gcloud-cli"
  depends_on "helm"
  depends_on "kubernetes-cli"
  depends_on "minikube"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.0/homebrew-kubefs_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cb521e6c2c19e461b48bec011c8740f98a853d773052c268dbbe8155a8cb79ed"

      def install
        bin.install "kubefs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.0/homebrew-kubefs_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0f739b1836c650b0ad428b12ec408996c404a0b406785d59d95d9f83ea5978ab"

      def install
        bin.install "kubefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.0/homebrew-kubefs_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "3c6b190a56c02d40e65b59c75915bcb7dfeb3b6dc1b07a389ecb36ddac938b3e"

        def install
          bin.install "kubefs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.0/homebrew-kubefs_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "8b3285f6db7f3a0389feb6c2512f5ced708d616ec88004832e042c49eab729e6"

        def install
          bin.install "kubefs"
        end
      end
    end
  end

  def caveats
    <<~EOS
      kubefs is a cli tool to simplify the process of creating, testing, and deploying full stack applications onto kubernetes clusters.
      Visit https://github.com/rahulmedicharla/kubefs to get started.
    EOS
  end

  test do
    system "#{bin}/kubefs --help"
    # ...
  end
end
