# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefs < Formula
  desc "a cli tool to simplify the process of creating, testing, and deploying full stack applications onto kubernetes clusters."
  homepage "https://github.com/rahulmedicharla/kubefs"
  version "1.10"
  license "MIT"

  depends_on "helm"
  depends_on "minikube"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.10/homebrew-kubefs_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6d8b80b8d27bd5055136212fcee2926f85715cd68e86497af4df82b08f146beb"

      def install
        bin.install "kubefs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.10/homebrew-kubefs_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7236b9dc32d91bf77c65a1fddefd51646520c226371c0dd8a58bcbc4567d127e"

      def install
        bin.install "kubefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.10/homebrew-kubefs_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "5942e15c9cec021851bef8e1d1ba4fbf6fc5fb1434c8bed15e838cc32d8c39fa"

        def install
          bin.install "kubefs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.10/homebrew-kubefs_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "69c4d935c0ca1f5abc65a5017977883efa933515513aa6fdfe6fb1deeecc532a"

        def install
          bin.install "kubefs"
        end
      end
    end
  end

  def caveats
    <<~EOS
      kubefs is a cli tool to simplify the process of creating, testing, and deploying full stack applications onto kubernetes clusters.
      Visit https://github.com/rahulmedicharla/kubefs to get started.
    EOS
  end

  test do
    system "#{bin}/kubefs --help"
    # ...
  end
end
