# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefs < Formula
  desc "a cli tool to simplify the process of creating, testing, and deploying full stack applications onto kubernetes clusters."
  homepage "https://github.com/rahulmedicharla/kubefs"
  version "1.2.1"
  license "MIT"

  depends_on "helm"
  depends_on "kubernetes-cli"
  depends_on "minikube"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.1/homebrew-kubefs_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b106043bfbb3ccca8260c7f62f570999d7cb756c3bc270b7bd802f9e83e33a10"

      def install
        bin.install "kubefs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.1/homebrew-kubefs_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "87c58063b680a9182cf577b0ba6473d2b35d679eab27dc40854f7155ccc4f31f"

      def install
        bin.install "kubefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.1/homebrew-kubefs_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "32ff5021bec08a0cdd7feb44f8566aef9a310cf5e26cd10ef687516d4b90c336"

        def install
          bin.install "kubefs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rahulmedicharla/homebrew-kubefs/releases/download/v1.2.1/homebrew-kubefs_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "1d3f1c0263780c21d79ac405feb2cc30e0d13b85a493c312d043aa62a6b3ef64"

        def install
          bin.install "kubefs"
        end
      end
    end
  end

  def caveats
    <<~EOS
      kubefs is a cli tool to simplify the process of creating, testing, and deploying full stack applications onto kubernetes clusters.
      Visit https://github.com/rahulmedicharla/kubefs to get started.
    EOS
  end

  test do
    system "#{bin}/kubefs --help"
    # ...
  end
end
