apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  clusterIP: None  # This makes the service headless
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deployment.selectorLabels" . | nindent 4 }}