apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.image.repository }}-storage
provisioner: rancher.io/local-path
# parameters:
#   type: pd-ssd
volumeBindingMode: WaitForFirstConsumer