apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment.fullname" . }}-traefik-config
  namespace: {{ .Values.namespace }}
data:
  traefik.yml: |
    http:
      routers:
        frontend:
          rule: "PathPrefix(`/`)"
          service: frontend
        backend:
          rule: "PathPrefix(`/env`)"
          service: backend
      services:
        frontend:
          loadBalancer:
            servers:
              - url: "http://localhost:{{ .Values.service.port }}"
        backend:
          loadBalancer:
            servers:
              - url: "http://localhost:{{ .Values.kubefsEnv.port }}"