apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "deployment.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local